version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  api:
    restart: always
    depends_on:
      - elasticsearch
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - ES_HOST=http://elasticsearch:9200
  ui:
    depends_on:
      - api
    build:
      context: ./ui
      dockerfile: Dockerfile
      args: 
        VUE_APP_API_URL: http://localhost:8080
    ports:
      - 80:80
